---
title: "ESM 244 Lab 3 Part 2: kriging!"
author: "Chelsea Sanford"
format: 
  html:
    code-fold: show
    toc: true
    number-sections: true
    embed-resources: true #this puts the html and figures together (like plots etc) * remember from now on
editor: visual
excecute: 
  echo: true
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
library(here)
library(broom) 

### spatial packages
library(sf) ### vector spatial data
library(terra) ### raster spatial data
library(tidyterra) ### for rasters in ggplot
###geospatial stats:
library(gstat)
library(stars)
```

# Overview

Create a variogram in R to understand the spatial dependece of groundwater depth in CA.

# Read in the data!

```{r}
ca_counties_sf <- read_sf(here('data', 'ca_counties'), layer = 'CA_Counties_TIGER2016') %>% #no .shp when using layer
  janitor::clean_names() %>% 
  select(name)

ca_dgw_sf <- read_sf(here('data', 'ca_dgw',
                      'F2013_DBGS_Points_20150720_093252.gpkg'))
```

```{r}
# st_crs(ca_counties_sf)
# st_crs(ca_dgw_sf) # ID["EPSG",4326]]

ca_dgw_sf <- st_transform(ca_dgw_sf, 3857) %>% 
  rename(depth = dgbs)

ggplot() +
  geom_sf(data = ca_counties_sf) +
  geom_sf(data = ca_dgw_sf, aes(color = depth))
```

# Focus on San Joaquin County

```{r}
sj_county_sf <- ca_counties_sf %>% 
  filter(name == 'San Joaquin')

sj_depth_sf <- ca_dgw_sf %>% 
  st_intersection(sj_county_sf)

ggplot() +
  geom_sf(data = sj_county_sf) +
  geom_sf(data = sj_depth_sf, aes(color = depth)) + 
  theme_void()
```

# Spatial interpolation

## Make a variogram

```{r}
sj_dgw_vgm <- gstat::variogram(depth ~ 1, data = sj_depth_sf) # depth~1 only includes depth, but depth ~ elevation would mean integrate elevation as well (two variables instead of 1)
plot(sj_dgw_vgm)

vgm_fit <- fit.variogram(sj_dgw_vgm,
                         model = vgm(model = 'Gau', nugget = TRUE)) # more accurate nugget. default nugget = 0

plot(sj_dgw_vgm, vgm_fit)

attr(vgm_fit, 'SSErr') # sum of squared errors (lower is a better fit of the variogram)
```

```{r}
sj_grid <- st_bbox(sj_county_sf) %>% 
  stars::st_as_stars(dx = 1000, dy = 1000) #will not look like anything

dgw_krige <- krige(depth ~ 1, sj_depth_sf, sj_grid, model = vgm_fit) #krige predict the depth in areas around the known locations based on the grid that we outlined

plot(dgw_krige)
```

```{r}
krige_rast <- dgw_krige %>% 
  terra::rast() %>% 
  setNames(c('pred', 'var'))

ggplot() +
  tidyterra::geom_spatraster(data = krige_rast, aes(fill = pred)) +
  geom_sf(data = sj_depth_sf, aes(fill = depth), shape = 21) +
  geom_sf(data = sj_county_sf, color = 'black', fill = NA) +
  scale_fill_gradient(low = 'blue', high = 'yellow') + 
  theme_void()
```

